---
- name: Self-service SSH keypair import/create
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
  - name: Show key_action
    debug:
      var: key_action

  - name: Show user_public_key
    debug:
      var: user_public_key

  - name: Show JSON representation
    debug:
      msg: "{{ user_public_key | to_json }}"

  - name: Test regex
    debug:
      msg: "{{ (user_public_key | trim) is match('^(ssh-rsa|ssh-ed25519|ecdsa-sha2-\\S+)\\s+\\S+') }}"

  - name: Validate pasted public key format
    assert:
      that:
        - (user_public_key | trim) is match('^(ssh-rsa|ssh-ed25519|ecdsa-sha2-\\S+)\\s+\\S+')
      fail_msg: "Invalid public key"

  - name: Import user's existing public key
    openstack.cloud.keypair:
      state: present
      name: "{{ keypair_name }}"
      public_key: "{{ user_public_key }}"
    when: key_action == "import"

  - name: Generate a new keypair in OpenStack
    openstack.cloud.keypair:
      state: present
      name: "{{ keypair_name }}"
    register: kp
    no_log: true
    when: key_action == "create"

  - name: Show private key (save this now — it cannot be retrieved again)
    ansible.builtin.debug:
      msg: "{{ kp.keypair.private_key }}"
    when:
      - key_action == "create"
      - kp.keypair.private_key is defined
